print ("______________________________________________________")
item1 = str(input("Digite o item 1: "))
print ("______________________________________________________")
valor1 = float(input(f"Digite o valor de {item1}: R$"))
print ("______________________________________________________")
item2 = str(input("Digite o item 2: "))
print ("______________________________________________________")
valor2 = float(input(f"Digite o valor de {item2}: R$"))
print ("______________________________________________________")
item3 = str(input("Digite o item 3: "))
print ("______________________________________________________")
valor3 = float(input(f"Digite o valor de {item3}: R$"))
print ("______________________________________________________")
item4 = str(input("Digite o item 4: "))
print ("______________________________________________________")
valor4 = float(input(f"Digite o valor de {item4}: R$"))
print ("______________________________________________________")
item5 = str(input("Digite o item 5: "))
print ("______________________________________________________")
valor5 = float(input(f"Digite o valor de {item5}: R$"))

valortotal = (valor1 + valor2 + valor3 + valor4 + valor5)

print ("____________________")
print ("Lista de compra:")
print ("____________________")
print (f"{item1} R${valor1} ")
print ("____________________")
print (f"{item2} R${valor2} ")
print ("____________________")
print (f"{item3} R${valor3} ")
print ("____________________")
print (f"{item4} R${valor4} ")
print ("____________________")
print (f"{item5} R${valor5} ")
print ("____________________")
print (f"O valor total de {item1}, {item2}, {item3}, {item4} e {item5} é: R${valortotal:.2f}! vai tirar {valortotal:.2f} de onde? Nós somos pobres irmão.")
print ("____________________")

